### ISSUE TITLE
@sironeko0nyaの反応がないので403か502であるか確認する

### ISSUE THREAD

**Issue by ymzk-jp** [ISC-MakeIT/f_college_api#34]
Today at 9:04 AM ふむふむ　了解ですを最後に消息が途絶えた
二度寝の恐れもあり死活監視の導入も検討する

**Comment by fumihumi** [comment]
🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 
📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 📲 
📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞 📞

**Comment by fumihumi** [comment]
koba restartに成功し200
