### ISSUE TITLE
お腹が空いてきたのでKober Eatsが望まれる

### ISSUE THREAD

**Issue by ymzk-jp** [ISC-MakeIT/f_college_api#35]
@sironeko0nya at 9:04 AM
ふむふむ　了解です
を最後に消息が途絶えた
合わせて我々の小腹が空いてきたのでKober Eatsを所望する

**Comment by fumihumi** [comment]
🍕 🍰 🥞 🍕

**Comment by ymzk-jp** [comment]
ちょろっきーによって満たされた
